In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('C:/Users/Wang/Desktop/Python4DataAnalysis/Final/test7.csv')

In [3]:
data.head()

,Unnamed: 0,jobTitle,cmpName,cmpRating,cmpReviewsAmount,cmpReviews,cmpEmployees,jobCity,jobRegion,jobState,...,shark,shell,spark,splunk,spotfire,sps,spss,sql,tableau,zookeeper
0,1,"Data Scientist - growth, marketing research - ...",CyberCoders,3.5,18.0,As a selection representative you figure out h...,NaN,San-Francisco,San Francisco,CA,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,2,Data Scientist (macys.com),Macy’s,NaN,NaN,NaN,NaN,San-Francisco,San Francisco,CA,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,3,Data Scientist,The Judge Group,3.4,82.0,The recruiter always called me back whenever i...,201 to 500,San-Francisco,San Francisco,CA,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,Data Scientist - Big Data Immediate Need,Company is into Data Analytics,NaN,NaN,NaN,NaN,San-Francisco,San Mateo,CA,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,Data Scientist- Multiple States,Technical Consulting Firm,5.0,1.0,Great job security until they decided to close...,NaN,San-Francisco,San Francisco,CA,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [65]:
data.loc[0,'cmpReviews'][:600]

'As a selection representative you figure out how to construct your business starting with no outside help. You buckle down putting in 10-12 hour days, yet it will pay off in the event that you keep at it. Try not to enter this occupation supposing you can bear to be lethargic else you WILL fizzle. Great commission setup is fine for a few people however unquestionably not everybody. Youthful air and positive vibes all around.Fun culture and work environmentGreat money opportunityGreat growth opportunityUnlimited SnacksAbility to work remoteGreat company partiesCyberCoders is a solid culture com'

In [82]:
type(data[data['cmpReviews'].notnull()].loc[0])

pandas.core.series.Series

In [101]:
(data[data['cmpReviews'].notnull()]).iloc[800].head()

Unnamed: 0                 5253
jobTitle            GIS Analyst
cmpName                agilisIT
cmpRating                     4
cmpReviewsAmount              2
Name: 5252, dtype: object

In [37]:
import requests, json

In [67]:
import indicoio
indicoio.config.api_key = 'c6ef58328ddb406eb8f61ea9012d28ae'

# single example
indicoio.sentiment_hq(data.loc[2,'cmpReviews'])

0.5445394516000001

In [72]:
cmpData = pd.DataFrame(columns=['company','review_scores'])
cmpData.head()

Empty DataFrame
Columns: [company, review_scores]
Index: []

In [77]:
data.loc[1,'cmpReviews'] == 'nan'

False

In [103]:
for n in range(0,801):
    cmpData.loc[n] = [data[data['cmpReviews'].notnull()].iloc[n]['cmpName'],data[data['cmpReviews'].notnull()].iloc[n]['cmpReviews']]
cmpData.drop_duplicates()
cmpData.head()

,company,review_scores
0,CyberCoders,As a selection representative you figure out h...
1,The Judge Group,The recruiter always called me back whenever i...
2,Technical Consulting Firm,Great job security until they decided to close...
3,"Pfizer, Inc.",A typical day at work - checkin with your team...
4,SLAC National Accelerator Laboratory,SLAC is a wonderful place to work. SLAC is a ...

In [104]:
len(cmpData)

801

In [105]:
cmpData.to_csv('C:/Users/Wang/Desktop/Python4DataAnalysis/Final/cmpData.csv', encoding='utf-8')

In [113]:
cmpData.drop_duplicates(subset = ['review_scores'],keep = False)
cmpData

,company,review_scores
0,CyberCoders,As a selection representative you figure out h...
1,The Judge Group,The recruiter always called me back whenever i...
2,Technical Consulting Firm,Great job security until they decided to close...
3,"Pfizer, Inc.",A typical day at work - checkin with your team...
4,SLAC National Accelerator Laboratory,SLAC is a wonderful place to work. SLAC is a ...
5,Experis,Good experience. Professional and helpful. S...
6,Novartis,Busy from start to end however I enjoy as I li...
7,Apex Systems,Boston Medical Center was a great company to w...
8,"The Judge Group, Inc.",The recruiter always called me back whenever i...
9,"Amgen, Inc","Checked animals for health and welfare, study ..."
10,Workday Inc.,"I've worked for other software giants, and no ..."
11,Scientific Search,"Recruiter mislead me, gave incorrect informati..."
12,Enterprise Solution inc,Good place to work. Excellent work culture. Gr...
13,Autodesk Inc.,"Super smart people, world-changing technology...."
14,The Climate Corporation,I love the level of talent at this company and...
15,DNV GL,A nice company that's going through a lot of c...
16,Pinterest,Don't expect job security even though they wil...
17,Thomson Reuters,Thomson Reuters provides very good work life b...
18,"Salesforce.com, Inc.",Amazing industry with great growth potential. ...
19,Doximity,Great team spirit; enjoyable place to workCo-w...
20,Verizon,Constant tracking of percent to goals to ensur...
21,Postmates,I turn on the app and start getting request to...
22,Tapjoy,I am on contract so my experience is not from ...
23,City & County of San Francisco,I supervised up to 15 team members. Each day ...
24,Genentech,"Like any big company there are pros and cons, ..."
25,Dropbox,"Overall smart, but humble group of people who ..."
26,Chegg,"It's easy going, you choose when to take tutor..."
27,The Gap,They were very friendly and made the work envi...
28,AutoDesk,"Super smart people, world-changing technology...."
29,Google,"Great place to work, unbelievable amenities, g..."
...,...,...
769,Apache,If everyday is the same then we are doing our ...
770,EOG Resources,My 18 years with the EOG family was incredible...
771,Southern Union Company,Handled daily cash flow for several large comp...
772,Veolia,"good company to work for, takes care of employ..."
773,Rice University,Very collaborative and a great place to learn ...
774,Cyberonics,"As Cyberonics, it was an excellent place to wo..."
775,MD Anderson Cancer Center,There really isn't a typical day in dining ser...
776,"ERM Group, Inc.",Partner oriented organization with a strong em...
777,Apache Corp,I am very thankful to have had the opportunity...
778,Hess,Manage the station. controling of inventory an...
779,Real Staffing,Great company to work for. Would work for the...
780,MilliporeSigma,Large company with various opportunities and r...
781,Ionis Pharmaceuticals,Started off great but the culture changed and ...
782,Tealium,"You could do better. Culture is very spotty, t..."
783,OneRoof Energy,No room for growth unless you know someone or ...
784,"Sequenom, Inc.",Mostly good people to work with and the job wa...
785,General Atomics,The biggest issue was co-workers. They spent ...
786,Integrated Resources INC,Caring staff and Intelligent managers make SH ...
789,Zoetis,Everyone is very welcoming and nice. However t...
790,"Affymetrix, Inc.",Affymetrix was acquired by another company so ...
791,"Kelly Services, Inc.",great company to work with I have no complains...
792,Kaztronix LLC,I like to be busy.I typically am accountable (...
793,BASF,Dealt with a high volume of inbound calls from...
794,Pluralsight,"I love my job, I love what my company stands f..."
795,Monsanto,Long work daysGet people to work withGet to wo...
796,Accelrys Inc,Manager is aweful..company is good. Team is go...
797,Rangam Consultants Inc,*Ranam Consultants is a hiring agency based ou...
798,Artech Information Systems,"Overall a good experience, some things could h..."
799,Vertex Pharmaceuticals,The company has the best benefits for employee...
800,agilisIT,Management truly wants to hear our input and m...

In [115]:
for n in range(0,767):
    cmpData.iloc[n]['review_scores'] = indicoio.sentiment_hq(cmpData.iloc[n]['review_scores'])

cmpData

                                  company review_scores
0                             CyberCoders       0.84038
1                         The Judge Group      0.544539
2               Technical Consulting Firm      0.501968
3                            Pfizer, Inc.      0.985908
4    SLAC National Accelerator Laboratory      0.997413
5                                 Experis      0.907323
6                                Novartis       0.97129
7                            Apex Systems      0.530823
8                   The Judge Group, Inc.      0.845791
9                              Amgen, Inc      0.896511
10                           Workday Inc.     0.0685299
11                      Scientific Search    0.00832815
12                Enterprise Solution inc      0.999458
13                          Autodesk Inc.      0.985475
14                The Climate Corporation      0.994055
15                                 DNV GL      0.965048
16                              Pinterest     0.0767563
17                        Thomson Reuters      0.991001
18                   Salesforce.com, Inc.      0.996645
19                               Doximity      0.993524
20                                Verizon      0.991245
21                              Postmates       0.88852
22                                 Tapjoy      0.874986
23         City & County of San Francisco      0.986221
24                              Genentech      0.999607
25                                Dropbox      0.997673
26                                  Chegg      0.790759
27                                The Gap       0.99895
28                               AutoDesk      0.992026
29                                 Google       0.99617
..                                    ...           ...
769                                Apache      0.998904
770                         EOG Resources        0.9985
771                Southern Union Company      0.985923
772                                Veolia      0.987399
773                       Rice University       0.96224
774                            Cyberonics     0.0562407
775             MD Anderson Cancer Center      0.955641
776                       ERM Group, Inc.       0.67181
777                           Apache Corp      0.998022
778                                  Hess      0.986027
779                         Real Staffing      0.992654
780                        MilliporeSigma      0.996713
781                 Ionis Pharmaceuticals      0.786309
782                               Tealium    0.00911286
783                        OneRoof Energy      0.965478
784                        Sequenom, Inc.       0.57666
785                       General Atomics      0.997284
786              Integrated Resources INC      0.969694
789                                Zoetis      0.987047
790                      Affymetrix, Inc.       0.98196
791                  Kelly Services, Inc.      0.896466
792                         Kaztronix LLC      0.332478
793                                  BASF      0.966085
794                           Pluralsight      0.994312
795                              Monsanto      0.970186
796                          Accelrys Inc     0.0570924
797                Rangam Consultants Inc      0.946317
798            Artech Information Systems      0.920242
799                Vertex Pharmaceuticals      0.845508
800                              agilisIT      0.996528

[767 rows x 2 columns]

In [116]:
for n in range(0,767):
    cmpData.iloc[n]['review_scores'] = "%.2f" % (cmpData.iloc[n]['review_scores'] * 100)
cmpData

                                  company review_scores
0                             CyberCoders         84.04
1                         The Judge Group         54.45
2               Technical Consulting Firm         50.20
3                            Pfizer, Inc.         98.59
4    SLAC National Accelerator Laboratory         99.74
5                                 Experis         90.73
6                                Novartis         97.13
7                            Apex Systems         53.08
8                   The Judge Group, Inc.         84.58
9                              Amgen, Inc         89.65
10                           Workday Inc.          6.85
11                      Scientific Search          0.83
12                Enterprise Solution inc         99.95
13                          Autodesk Inc.         98.55
14                The Climate Corporation         99.41
15                                 DNV GL         96.50
16                              Pinterest          7.68
17                        Thomson Reuters         99.10
18                   Salesforce.com, Inc.         99.66
19                               Doximity         99.35
20                                Verizon         99.12
21                              Postmates         88.85
22                                 Tapjoy         87.50
23         City & County of San Francisco         98.62
24                              Genentech         99.96
25                                Dropbox         99.77
26                                  Chegg         79.08
27                                The Gap         99.89
28                               AutoDesk         99.20
29                                 Google         99.62
..                                    ...           ...
769                                Apache         99.89
770                         EOG Resources         99.85
771                Southern Union Company         98.59
772                                Veolia         98.74
773                       Rice University         96.22
774                            Cyberonics          5.62
775             MD Anderson Cancer Center         95.56
776                       ERM Group, Inc.         67.18
777                           Apache Corp         99.80
778                                  Hess         98.60
779                         Real Staffing         99.27
780                        MilliporeSigma         99.67
781                 Ionis Pharmaceuticals         78.63
782                               Tealium          0.91
783                        OneRoof Energy         96.55
784                        Sequenom, Inc.         57.67
785                       General Atomics         99.73
786              Integrated Resources INC         96.97
789                                Zoetis         98.70
790                      Affymetrix, Inc.         98.20
791                  Kelly Services, Inc.         89.65
792                         Kaztronix LLC         33.25
793                                  BASF         96.61
794                           Pluralsight         99.43
795                              Monsanto         97.02
796                          Accelrys Inc          5.71
797                Rangam Consultants Inc         94.63
798            Artech Information Systems         92.02
799                Vertex Pharmaceuticals         84.55
800                              agilisIT         99.65

[767 rows x 2 columns]

In [119]:
cmpData.index=(range(767))
cmpData

                                  company review_scores
0                             CyberCoders         84.04
1                         The Judge Group         54.45
2               Technical Consulting Firm         50.20
3                            Pfizer, Inc.         98.59
4    SLAC National Accelerator Laboratory         99.74
5                                 Experis         90.73
6                                Novartis         97.13
7                            Apex Systems         53.08
8                   The Judge Group, Inc.         84.58
9                              Amgen, Inc         89.65
10                           Workday Inc.          6.85
11                      Scientific Search          0.83
12                Enterprise Solution inc         99.95
13                          Autodesk Inc.         98.55
14                The Climate Corporation         99.41
15                                 DNV GL         96.50
16                              Pinterest          7.68
17                        Thomson Reuters         99.10
18                   Salesforce.com, Inc.         99.66
19                               Doximity         99.35
20                                Verizon         99.12
21                              Postmates         88.85
22                                 Tapjoy         87.50
23         City & County of San Francisco         98.62
24                              Genentech         99.96
25                                Dropbox         99.77
26                                  Chegg         79.08
27                                The Gap         99.89
28                               AutoDesk         99.20
29                                 Google         99.62
..                                    ...           ...
737                                Apache         99.89
738                         EOG Resources         99.85
739                Southern Union Company         98.59
740                                Veolia         98.74
741                       Rice University         96.22
742                            Cyberonics          5.62
743             MD Anderson Cancer Center         95.56
744                       ERM Group, Inc.         67.18
745                           Apache Corp         99.80
746                                  Hess         98.60
747                         Real Staffing         99.27
748                        MilliporeSigma         99.67
749                 Ionis Pharmaceuticals         78.63
750                               Tealium          0.91
751                        OneRoof Energy         96.55
752                        Sequenom, Inc.         57.67
753                       General Atomics         99.73
754              Integrated Resources INC         96.97
755                                Zoetis         98.70
756                      Affymetrix, Inc.         98.20
757                  Kelly Services, Inc.         89.65
758                         Kaztronix LLC         33.25
759                                  BASF         96.61
760                           Pluralsight         99.43
761                              Monsanto         97.02
762                          Accelrys Inc          5.71
763                Rangam Consultants Inc         94.63
764            Artech Information Systems         92.02
765                Vertex Pharmaceuticals         84.55
766                              agilisIT         99.65

[767 rows x 2 columns]

In [123]:
cmpData.sort_values(by='review_scores', ascending=False,inplace=True)
cmpData.head()

                            company review_scores
24                        Genentech         99.96
12          Enterprise Solution inc         99.95
553                     Capital One         99.93
118                           Roche         99.93
501  North Shore Long Island Jewish         99.92

In [127]:
len(data.loc[0]['cmpReviews'])

8444

In [129]:
cmpData1 = pd.DataFrame(columns=['company','city','review_scores'])
cmpData1.head()

Empty DataFrame
Columns: [company, city, review_scores]
Index: []

In [140]:
# for n in range(0,len(data[len(data['cmpReviews'])>5000])):
#     cmpData1.loc[n] = [[data[len(data['cmpReviews'])>5000]].iloc[n]['cmpName'],data[len(data['cmpReviews'])>5000].iloc[n]['jobCity'],data[len(data['cmpReviews'])>5000].iloc[n]['cmpReviews']]

# cmpData.head()

In [142]:
cmpData1 = data
for n in range(0,len(data)):
    if len(data.loc[n]['cmpReviews'])<4000:
        cmpData1.drop[cmpData1.index[n]]
len(cmpData1)

TypeError: object of type 'float' has no len()

In [144]:
data.head()

,Unnamed: 0,jobTitle,cmpName,cmpRating,cmpReviewsAmount,cmpReviews,cmpEmployees,jobCity,jobRegion,jobState,...,shark,shell,spark,splunk,spotfire,sps,spss,sql,tableau,zookeeper
0,1,"Data Scientist - growth, marketing research - ...",CyberCoders,3.5,18.0,As a selection representative you figure out h...,NaN,San-Francisco,San Francisco,CA,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,2,Data Scientist (macys.com),Macy’s,NaN,NaN,NaN,NaN,San-Francisco,San Francisco,CA,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,3,Data Scientist,The Judge Group,3.4,82.0,The recruiter always called me back whenever i...,201 to 500,San-Francisco,San Francisco,CA,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,Data Scientist - Big Data Immediate Need,Company is into Data Analytics,NaN,NaN,NaN,NaN,San-Francisco,San Mateo,CA,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,Data Scientist- Multiple States,Technical Consulting Firm,5.0,1.0,Great job security until they decided to close...,NaN,San-Francisco,San Francisco,CA,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0